### ISSUE TITLE
请问怎么添加自定义校验规则？

### ISSUE THREAD

**Issue by lvzhihao100** [yoojia/NextInputs-Android#2]

**Comment by cheetah747** [comment]
配置gradle报错。。。。配的1.6-final

**Comment by yoojia** [comment]
Sorry，版本问题应该是文档写错了。

自定义校验规则见最新master分支的示例代码。

`compile 'com.github.yoojia:next-inputs-android:1.7.1'`

`
// 自定义校验规则
// 1. 跟上面一样，指定需要校验的View；
// 2. 通过Scheme.create方法，创建Verifier校验器，校验器实现具体的校验规则；
inputs.add(access.findTextView(R.id.form_field_14), Scheme.create(new Verifier() {
    @Override
    public boolean perform(String rawInput) throws Exception {
        return "对输入内容进行自定义规则校验".equals(rawInput);
    }
}));
`
